config()
{
    cmake -DUNWIND_INCLUDE_DIR=$LIBUNWIND_DIR/include -DUNWIND_LIBRARY=$LIBUNWIND_DIR/lib/libunwind.so -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-g -O3 -Wno-unused-result" .
}
